name: Automatic Preprocessing Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Langkah 1: Ambil kode dari repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Langkah 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Sesuaikan jika Anda pakai versi lain

      # Langkah 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      # Langkah 4: Jalankan skrip preprocessing
      # Pastikan skrip dijalankan dari root agar path './namadataset_raw/' dan 'preprocessing/...' bekerja
      - name: Run Preprocessing Script
        run: python preprocessing/automate_muhammadnanda.py

      # Langkah 5: Commit dan Push hasil preprocessing & model
      - name: Commit and Push Results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add preprocessing/preprocessing_datasets/*
          git add preprocessing/model/*
          # Hanya commit jika ada perubahan pada file yang di-add
          git diff --staged --quiet || git commit -m "Advance: Update preprocessed data & models via Actions"
          git push
